window.INTEGRATED_APPS = [
  {
    id: "renrakucho",
    title: "連絡帳作成",
    description: "小学校の連絡帳用紙に合わせて、薄い見本文字を作成して印刷できます。",
    category: "学校",
    grades: ["all"],
    tags: ["連絡帳", "印刷", "PDF"],
    href: "apps/renrakucho/index.html",
    actionLabel: "連絡帳を作る",
    status: "ready",
    accent: "#0072bc",
  },
  {
    id: "kanji-print",
    title: "漢字なぞりプリント",
    description: "文章から漢字練習用のなぞりプリントを作成して印刷できます。",
    category: "教材",
    grades: ["all"],
    tags: ["漢字", "なぞり", "印刷"],
    href: "apps/kanji-print/index.html",
    actionLabel: "プリントを作る",
    status: "ready",
    accent: "#0f7b5f",
  },
  {
    id: "math-print-grade1",
    title: "1年生 計算プリント",
    description: "小学1年生向けのたし算・ひき算プリントを自動作成して印刷できます。",
    category: "教材",
    grades: ["1"],
    tags: ["計算", "1年生", "印刷"],
    href: "apps/math-print-grade1/index.html",
    actionLabel: "計算プリントを作る",
    status: "ready",
    accent: "#b45f06",
  },
  {
    id: "number-print-grade1",
    title: "1年生 かず",
    description: "数を数える、順番、数の大小を練習するプリントを作成できます。",
    category: "教材",
    grades: ["1"],
    tags: ["算数", "1年生", "かず", "順番", "印刷"],
    href: "apps/number-print-grade1/index.html",
    actionLabel: "かずプリントを作る",
    status: "ready",
    accent: "#0f766e",
  },
  {
    id: "clock-print-grade1",
    title: "1年生 とけい",
    description: "なんじ、なんじはんの読み取りや針をかくプリントを作成できます。",
    category: "教材",
    grades: ["1"],
    tags: ["算数", "1年生", "時計", "時刻", "印刷"],
    href: "apps/clock-print-grade1/index.html",
    actionLabel: "とけいプリントを作る",
    status: "ready",
    accent: "#2563eb",
  },
  {
    id: "math-print-grade2",
    title: "2年生 計算プリント",
    description: "小学2年生向けの2けた計算と九九のプリントを自動作成して印刷できます。",
    category: "教材",
    grades: ["2"],
    tags: ["計算", "2年生", "九九", "筆算", "印刷"],
    href: "apps/math-print-grade2/index.html",
    actionLabel: "2年生プリントを作る",
    status: "ready",
    accent: "#2f7d6d",
  },
  {
    id: "time-print-grade2",
    title: "2年生 時刻・時間",
    description: "時計を読む、針を描く、何分後・何分前を考えるプリントを作成できます。",
    category: "教材",
    grades: ["2"],
    tags: ["算数", "2年生", "時刻", "時間", "印刷"],
    href: "apps/time-print-grade2/index.html",
    actionLabel: "時刻プリントを作る",
    status: "ready",
    accent: "#2563eb",
  },
  {
    id: "length-print-grade2",
    title: "2年生 長さ",
    description: "cm、mm、mの読み取りや単位換算、長さ比べのプリントを作成できます。",
    category: "教材",
    grades: ["2"],
    tags: ["算数", "2年生", "長さ", "ものさし", "印刷"],
    href: "apps/length-print-grade2/index.html",
    actionLabel: "長さプリントを作る",
    status: "ready",
    accent: "#0f766e",
  },
  {
    id: "capacity-print-grade2",
    title: "2年生 水のかさ",
    description: "L、dL、mLの単位変換プリントを作成できます。",
    category: "教材",
    grades: ["2"],
    tags: ["算数", "2年生", "水のかさ", "単位変換", "印刷"],
    href: "apps/capacity-print-grade2/index.html",
    actionLabel: "単位変換プリントを作る",
    status: "ready",
    accent: "#0284c7",
  },
  {
    id: "table-graph-print-grade2",
    title: "2年生 表とグラフ",
    description: "簡単な表や棒グラフを読み取るプリントを作成できます。",
    category: "教材",
    grades: ["2"],
    tags: ["算数", "2年生", "表", "グラフ", "印刷"],
    href: "apps/table-graph-print-grade2/index.html",
    actionLabel: "表とグラフを作る",
    status: "ready",
    accent: "#c2410c",
  },
  {
    id: "math-print-grade3",
    title: "3年生 計算プリント",
    description: "3けた・4けたのたし算とひき算プリントを自動作成して印刷できます。",
    category: "教材",
    grades: ["3"],
    tags: ["算数", "3年生", "たし算", "ひき算", "筆算", "印刷"],
    href: "apps/math-print-grade3/index.html",
    actionLabel: "計算プリントを作る",
    status: "ready",
    accent: "#2563eb",
  },
  {
    id: "weight-print-grade3",
    title: "3年生 重さプリント",
    description: "kgとgの単位変換、重さのたし算・ひき算、重さ比べのプリントを作成できます。",
    category: "教材",
    grades: ["3"],
    tags: ["算数", "3年生", "重さ", "単位変換", "計算", "印刷"],
    href: "apps/weight-print-grade3/index.html",
    actionLabel: "重さプリントを作る",
    status: "ready",
    accent: "#8b5cf6",
  },
  {
    id: "time-print-grade3",
    title: "3年生 時刻と時間",
    description: "時間のたし算・ひき算と、分・秒の単位変換プリントを自動作成できます。",
    category: "教材",
    grades: ["3"],
    tags: ["算数", "3年生", "時刻", "時間", "秒", "計算", "印刷"],
    href: "apps/time-print-grade3/index.html",
    actionLabel: "時刻と時間を練習する",
    status: "ready",
    accent: "#2563eb",
  },
  {
    id: "division-print-grade3",
    title: "3年生 わり算プリント",
    description: "3年生向けのわり算プリントを作成できます。複数枚では別々の問題を生成します。",
    category: "教材",
    grades: ["3"],
    tags: ["算数", "3年生", "わり算", "印刷"],
    href: "apps/division-print-grade3/index.html",
    actionLabel: "わり算プリントを作る",
    status: "ready",
    accent: "#7c3aed",
  },
  {
    id: "multiplication-print-grade3",
    title: "3年生 かけ算の筆算",
    description: "2けた・3けたのかけ算筆算プリントを自動作成して印刷できます。",
    category: "教材",
    grades: ["3"],
    tags: ["算数", "3年生", "かけ算", "筆算", "印刷"],
    href: "apps/multiplication-print-grade3/index.html",
    actionLabel: "かけ算筆算を作る",
    status: "ready",
    accent: "#0f766e",
  },
  {
    id: "division-print-grade4",
    title: "4年生 わり算の筆算",
    description: "3桁を1桁で割る筆算プリントを、固定マス付きで自動作成できます。",
    category: "教材",
    grades: ["4"],
    tags: ["算数", "4年生", "わり算", "筆算", "あまり", "印刷"],
    href: "apps/division-print-grade4/index.html",
    actionLabel: "わり算筆算を作る",
    status: "ready",
    accent: "#0f766e",
  },
  {
    id: "decimal-print-grade4",
    title: "4年生 小数計算",
    description: "小数のたし算・ひき算と、小数×整数・小数÷整数のプリントを作成できます。",
    category: "教材",
    grades: ["4"],
    tags: ["算数", "4年生", "小数", "計算", "筆算", "印刷"],
    href: "apps/decimal-print-grade4/index.html",
    actionLabel: "小数計算を練習する",
    status: "ready",
    accent: "#0f766e",
  },
  {
    id: "multiplication-print-grade4",
    title: "4年生 かけ算の筆算",
    description: "3けた・4けたの数に2けた・3けたの数をかける筆算プリントを作成できます。",
    category: "教材",
    grades: ["4"],
    tags: ["算数", "4年生", "かけ算", "筆算", "印刷"],
    href: "apps/multiplication-print-grade4/index.html",
    actionLabel: "かけ算筆算を作る",
    status: "ready",
    accent: "#0f766e",
  },
  {
    id: "rounding-print-grade4",
    title: "4年生 がい数・四捨五入",
    description: "四捨五入と、がい数を使った計算の見積もりプリントを作成できます。",
    category: "教材",
    grades: ["4"],
    tags: ["算数", "4年生", "がい数", "四捨五入", "見積もり", "印刷"],
    href: "apps/rounding-print-grade4/index.html",
    actionLabel: "がい数を練習する",
    status: "ready",
    accent: "#c2410c",
  },
  {
    id: "decimal-print-grade5",
    title: "5年生 小数のかけ算・わり算",
    description: "小数×小数と、割り切れる小数÷小数のプリントを作成できます。",
    category: "教材",
    grades: ["5"],
    tags: ["算数", "5年生", "小数", "かけ算", "わり算", "印刷"],
    href: "apps/decimal-print-grade5/index.html",
    actionLabel: "小数計算を練習する",
    status: "ready",
    accent: "#2563eb",
  },
  {
    id: "number-properties-print-grade5",
    title: "5年生 約数・倍数",
    description: "偶数・奇数、倍数、約数、公倍数、公約数を練習するプリントを作成できます。",
    category: "教材",
    grades: ["5"],
    tags: ["算数", "5年生", "約数", "倍数", "公約数", "公倍数", "印刷"],
    href: "apps/number-properties-print-grade5/index.html",
    actionLabel: "約数・倍数を練習する",
    status: "ready",
    accent: "#7c3aed",
  },
  {
    id: "rates-print-grade5",
    title: "5年生 割合・平均・速さ",
    description: "平均、単位量あたり、割合・百分率、速さの計算プリントを作成できます。",
    category: "教材",
    grades: ["5"],
    tags: ["算数", "5年生", "割合", "平均", "速さ", "百分率", "印刷"],
    href: "apps/rates-print-grade5/index.html",
    actionLabel: "割合・平均・速さを練習する",
    status: "ready",
    accent: "#0284c7",
  },
  {
    id: "ratio-print-grade6",
    title: "6年生 比",
    description: "比を簡単にする、等しい比、空欄補充、比の値のプリントを作成できます。",
    category: "教材",
    grades: ["6"],
    tags: ["算数", "6年生", "比", "比の値", "計算", "印刷"],
    href: "apps/ratio-print-grade6/index.html",
    actionLabel: "比を練習する",
    status: "ready",
    accent: "#7c3aed",
  },
  {
    id: "area-volume-print-grade6",
    title: "6年生 面積・体積計算",
    description: "円の面積と、角柱・円柱の体積を計算するプリントを作成できます。",
    category: "教材",
    grades: ["6"],
    tags: ["算数", "6年生", "円", "面積", "角柱", "円柱", "体積", "印刷"],
    href: "apps/area-volume-print-grade6/index.html",
    actionLabel: "面積・体積を練習する",
    status: "ready",
    accent: "#c2410c",
  },
];

