window.PRINT_RESOURCES = [
  ...(Array.isArray(window.PRINT_RESOURCES) ? window.PRINT_RESOURCES : []),
  {
    id: "surapuri-grade6-math-hub",
    title: "小学6年生 算数プリント一覧",
    description: "6年生の算数単元をまとめて探せます。分数、比、円の面積、体積、比例、データなどの入口です。",
    url: "https://surapuri.jp/elementary_school06/",
    siteId: "surapuri",
    siteTitle: "すらぷり",
    subject: "算数",
    grades: ["6"],
    unit: "6年生まとめ",
    tags: ["6年生", "算数", "単元一覧", "特別支援", "スモールステップ"],
  },
  {
    id: "surapuri-fraction-multiply-grade6",
    title: "小学6年生 分数のかけ算",
    description: "分数と整数、分数同士のかけ算を、約分を含めて練習できます。",
    url: "https://surapuri.jp/elementary_school06/bunsu-kakezan/",
    siteId: "surapuri",
    siteTitle: "すらぷり",
    subject: "算数",
    grades: ["6"],
    unit: "分数のかけ算",
    tags: ["6年生", "分数", "かけ算", "約分", "計算"],
  },
  {
    id: "surapuri-fraction-division-grade6",
    title: "小学6年生 分数のわり算",
    description: "分数を整数で割る計算から、約分を含む分数のわり算まで練習できます。",
    url: "https://surapuri.jp/elementary_school06/bunsu-warizan/",
    siteId: "surapuri",
    siteTitle: "すらぷり",
    subject: "算数",
    grades: ["6"],
    unit: "分数のわり算",
    tags: ["6年生", "分数", "わり算", "約分", "計算"],
  },
  {
    id: "surapuri-data-grade6",
    title: "小学6年生 データの調べ方",
    description: "平均値、度数分布表、ヒストグラム、中央値などを段階的に練習できます。",
    url: "https://surapuri.jp/elementary_school06/data/",
    siteId: "surapuri",
    siteTitle: "すらぷり",
    subject: "算数",
    grades: ["6"],
    unit: "データの活用",
    tags: ["6年生", "データ", "平均値", "ヒストグラム", "表"],
  },
  {
    id: "sukiruma-grade6-math-hub",
    title: "小学6年生 算数ワーク",
    description: "6年生の分数計算、比、比例、円の面積、角柱・円柱などを単元別に探せます。",
    url: "https://sukiruma.net/work-san6nen/",
    siteId: "sukiruma",
    siteTitle: "すきるまドリル",
    subject: "算数",
    grades: ["6"],
    unit: "6年生まとめ",
    tags: ["6年生", "算数", "単元一覧", "無料", "ワーク"],
  },
  {
    id: "chibimusu-grade6-math-hub",
    title: "小学6年生 算数プリント一覧",
    description: "6年生の算数を学年別に探せる入口です。対称、円の面積、体積、縮図などをまとめて確認できます。",
    url: "https://happylilac.net/c-gakunen6.html",
    siteId: "chibimusu",
    siteTitle: "ちびむすドリル",
    subject: "算数",
    grades: ["6"],
    unit: "6年生まとめ",
    tags: ["6年生", "算数", "単元一覧", "無料", "復習"],
  },
];
