window.PRINT_RESOURCES = [
  ...(Array.isArray(window.PRINT_RESOURCES) ? window.PRINT_RESOURCES : []),
  {
    id: "surapuri-grade4-math-hub",
    title: "小学4年生 算数プリント一覧",
    description: "4年生の算数単元をまとめて探せます。小数、わり算、面積、図形、分数などの入口です。",
    url: "https://surapuri.jp/elementary_school04/",
    siteId: "surapuri",
    siteTitle: "すらぷり",
    subject: "算数",
    grades: ["4"],
    unit: "4年生まとめ",
    tags: ["4年生", "算数", "単元一覧", "特別支援", "スモールステップ"],
  },
  {
    id: "surapuri-decimal-grade4",
    title: "小学4年生 小数のしくみ",
    description: "小数の読み方、位取り、大きさ比べを段階的に練習できます。",
    url: "https://surapuri.jp/elementary_school04/02/",
    siteId: "surapuri",
    siteTitle: "すらぷり",
    subject: "算数",
    grades: ["4"],
    unit: "小数",
    tags: ["4年生", "小数", "位取り", "数の大きさ", "スモールステップ"],
  },
  {
    id: "sukiruma-grade4-math-hub",
    title: "小学4年生 算数ワーク",
    description: "4年生で学ぶ算数を単元別に探せる一覧です。計算、図形、分数、小数などの復習に使えます。",
    url: "https://sukiruma.net/work-san4nen/",
    siteId: "sukiruma",
    siteTitle: "すきるまドリル",
    subject: "算数",
    grades: ["4"],
    unit: "4年生まとめ",
    tags: ["4年生", "算数", "単元一覧", "無料", "ワーク"],
  },
  {
    id: "sukiruma-decimal-division-grade4",
    title: "小学4年生 小数のわり算",
    description: "小数を整数で割る計算と、筆算で小数点の位置を考える練習ができます。",
    url: "https://sukiruma.net/download-san4_syousuwa/",
    siteId: "sukiruma",
    siteTitle: "すきるまドリル",
    subject: "算数",
    grades: ["4"],
    unit: "小数のわり算",
    tags: ["4年生", "小数", "わり算", "筆算", "小数点"],
  },
  {
    id: "chibimusu-grade4-math-hub",
    title: "小学4年生 算数プリント一覧",
    description: "4年生の数と計算、図形、文章題などを単元別に探せる入口です。",
    url: "https://happylilac.net/c-gakunen4.html",
    siteId: "chibimusu",
    siteTitle: "ちびむすドリル",
    subject: "算数",
    grades: ["4"],
    unit: "4年生まとめ",
    tags: ["4年生", "算数", "単元一覧", "無料", "復習"],
  },
  {
    id: "chibimusu-division-column-grade4",
    title: "小学4年生 わり算の筆算",
    description: "3けたを1けたで割る筆算を、ガイド線あり・なしから選んで練習できます。",
    url: "https://happylilac.net/keisan-warizan45.html",
    siteId: "chibimusu",
    siteTitle: "ちびむすドリル",
    subject: "算数",
    grades: ["4"],
    unit: "わり算の筆算",
    tags: ["4年生", "わり算", "筆算", "商に0", "ガイド線"],
  },
  {
    id: "chibimusu-decimal-grade4",
    title: "小学4年生 小数の計算",
    description: "小数のしくみ、たし算・ひき算・かけ算・わり算のプリントを探せます。",
    url: "https://happylilac.net/syousu-bunsu.html",
    siteId: "chibimusu",
    siteTitle: "ちびむすドリル",
    subject: "算数",
    grades: ["4"],
    unit: "小数",
    tags: ["4年生", "小数", "筆算", "たし算", "ひき算"],
  },
  {
    id: "chibimusu-geometry-grade4",
    title: "小学4年生 図形・面積",
    description: "角の大きさ、垂直・平行、四角形、面積、直方体と立方体を練習できます。",
    url: "https://www.happylilac.net/zukei.html",
    siteId: "chibimusu",
    siteTitle: "ちびむすドリル",
    subject: "算数",
    grades: ["4"],
    unit: "図形・面積",
    tags: ["4年生", "図形", "面積", "角度", "直方体"],
  },
  {
    id: "jakka-kanji-grade4",
    title: "小学4年生 漢字練習・テスト",
    description: "4年生で習う漢字のなぞり、読み、書き取り、送り仮名、書き順を探せます。",
    url: "https://www.jakka.jp/main/4.htm",
    siteId: "jakka",
    siteTitle: "JAKKA",
    subject: "国語",
    grades: ["4"],
    unit: "漢字",
    tags: ["4年生", "漢字", "なぞり", "書き取り", "書き順"],
  },
];
