window.PRINT_RESOURCES = [
  ...(Array.isArray(window.PRINT_RESOURCES) ? window.PRINT_RESOURCES : []),
  {
    id: "surapuri-grade5-math-hub",
    title: "小学5年生 算数プリント一覧",
    description: "5年生の算数単元をまとめて探せます。小数、分数、体積、割合、平均などの入口です。",
    url: "https://surapuri.jp/elementary_school05/",
    siteId: "surapuri",
    siteTitle: "すらぷり",
    subject: "算数",
    grades: ["5"],
    unit: "5年生まとめ",
    tags: ["5年生", "算数", "単元一覧", "特別支援", "スモールステップ"],
  },
  {
    id: "surapuri-decimal-multiply-grade5",
    title: "小学5年生 小数のかけ算",
    description: "小数のかけ算を、筆算と小数点の位置を含めて段階的に練習できます。",
    url: "https://surapuri.jp/elementary_school05/02/",
    siteId: "surapuri",
    siteTitle: "すらぷり",
    subject: "算数",
    grades: ["5"],
    unit: "小数のかけ算",
    tags: ["5年生", "小数", "かけ算", "筆算", "小数点"],
  },
  {
    id: "surapuri-average-grade5",
    title: "小学5年生 平均",
    description: "平均の求め方や、平均からおよその量を考える問題を練習できます。",
    url: "https://surapuri.jp/elementary_school05/heikin/",
    siteId: "surapuri",
    siteTitle: "すらぷり",
    subject: "算数",
    grades: ["5"],
    unit: "平均",
    tags: ["5年生", "平均", "単位量あたり", "計算", "文章題"],
  },
  {
    id: "surapuri-fraction-decimal-grade5",
    title: "小学5年生 分数と小数・整数",
    description: "分数、小数、整数の関係や、分数で表す計算を練習できます。",
    url: "https://surapuri.jp/elementary_school05/bunsu-syousu-seisu/",
    siteId: "surapuri",
    siteTitle: "すらぷり",
    subject: "算数",
    grades: ["5"],
    unit: "分数",
    tags: ["5年生", "分数", "小数", "整数", "数の関係"],
  },
  {
    id: "sukiruma-grade5-math-hub",
    title: "小学5年生 算数ワーク",
    description: "5年生の小数計算、体積、約数・倍数、平均、割合、図形を単元別に探せます。",
    url: "https://sukiruma.net/work-san5nen/",
    siteId: "sukiruma",
    siteTitle: "すきるまドリル",
    subject: "算数",
    grades: ["5"],
    unit: "5年生まとめ",
    tags: ["5年生", "算数", "単元一覧", "無料", "ワーク"],
  },
  {
    id: "chibimusu-grade5-math-hub",
    title: "小学5年生 算数プリント一覧",
    description: "5年生の算数を学年別に探せる入口です。図形、体積、面積、円周などをまとめて確認できます。",
    url: "https://happylilac.net/c-gakunen5.html",
    siteId: "chibimusu",
    siteTitle: "ちびむすドリル",
    subject: "算数",
    grades: ["5"],
    unit: "5年生まとめ",
    tags: ["5年生", "算数", "単元一覧", "無料", "復習"],
  },
];
